# Generated by Django 5.0.6 on 2024-05-15 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('PS', 'PS'), ('SA', 'SA'), ('SB', 'SB'), ('SC', 'SC'), ('BG', 'BG')], default='PS', max_length=2)),
                ('industry', models.CharField(choices=[('FN', 'FN'), ('AG', 'AG'), ('TE', 'TE'), ('MO', 'MO')], default='FN', max_length=2)),
                ('location', models.CharField(choices=[('RW', 'RW'), ('GH', 'GH'), ('NG', 'NG')], default='RW', max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('capital', models.DecimalField(decimal_places=0, default=0, max_digits=15)),
                ('impact', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('sdg', models.JSONField(default=str)),
                ('values', models.JSONField(default=str)),
                ('expertise', models.JSONField(default=str)),
                ('strategy', models.JSONField(default=str)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('PS', 'PS'), ('SA', 'SA'), ('SB', 'SB'), ('SC', 'SC'), ('BG', 'BG')], default='PS', max_length=2)),
                ('industry', models.CharField(choices=[('FN', 'FN'), ('AG', 'AG'), ('TE', 'TE'), ('MO', 'MO')], default='FN', max_length=2)),
                ('location', models.CharField(choices=[('RW', 'RW'), ('GH', 'GH'), ('NG', 'NG')], default='RW', max_length=2)),
                ('name', models.CharField(max_length=50)),
                ('capital', models.DecimalField(decimal_places=0, max_digits=15)),
                ('impact', models.DecimalField(decimal_places=0, max_digits=10)),
                ('sdg', models.JSONField()),
                ('values', models.JSONField()),
                ('expertise', models.JSONField()),
                ('matching', models.JSONField()),
                ('strategy', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('starup_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
